### PR TITLE
Make python2 dependency explicit

### PR DESCRIPTION
**Pull request by dholl**
This naive pull request Addresses a near term need in issue #11, since Debian removed the ```python``` package and the ```/usr/bin/python``` interpreter but still supports ```python2``` and ```/usr/bin/python2```.

It is untested, but I'm willing to help with testing if the maintainers are interested and can provide some guidance.

Thank you,
David

### CODE REVIEW

**Comment by David-5-1** [comment]
Thanks for the report.
This looks harmless enough to be merged and should avoid issues in the short term.

Testing should be possible using http://mirrors.dev.gandi.net/gandi/ when the build is done (I will try to ping you back so that you can test).

Best regards,
David

**Comment by dholl** [comment]
I'll look forward to the ping for testing!  Regarding the mirrors.dev.gandi.net package repository, I briefly looked into it.  To prepare my system, is there a credible public place where the PGP/GPG key is published?

**Comment by David-5-1** [comment]
Hello,

sorry for the delay, I thought the easiest to provide the package from a trustable source was to have it directly on production mirror but not included in repository metadata even if I am confident with having it released. For the record, I had to push another change to packaging to support old distributions: 84702f2e8e48dbc6fb64a9d5b0f69de146768911

You can fetch the package last build which should fix the issue at https://mirrors.gandi.net/gandi/debian/pool/gandi-hosting-vm2_2.38_all.deb and should be able to install it with e.g. `apt install ./gandi-hosting-vm2_2.38_all.deb`.

**Comment by dholl** [comment]
I just downloaded and ran ```apt install ./gandi-hosting-vm2_2.38_all.deb```, so now I'm typing these notes, as I proceed through the remaining dependency issues:

Since the ```python``` package was still at version 2.7.17-2 (and thus less than 2.8), it was still considered a dependency of ```gandi-hosting-vm2 2.38```, and thus ```aptitude``` was still not releasing it even though ```python2``` is installed.  I told ```aptitude``` to just remove ```python```, and then that also released ```python-minimal```.  Then, my system somehow had ```libpython-stdlib``` marked as not-automatically installed, but once I marked it as auto, then ```aptitude``` finished upgrading these python2-related packages from 2.7.17-2 to 2.7.18-2:
	```libpython2-stdlib```
	```python2```
	```python2-minimal```

In conclusion, the happy ending is that the system didn't try to resolve any package problems by removing ```gandi-hosting-vm2```.  I didn't immediately notice any errors after these package updates, nor after rebooting in hopes of trying to provoke problems.

Thank you!  :-)

**Comment by David-5-1** [comment]
Thank you for your tests and feedback.

I think I had a few oddities when upgrading a machine after `python` to `python2` package switch in Debian, so I am not sure whether what you got was due to our package or not but the current stat should provide both an upgrade path and a way to reinstall `gandi-hosting-vm2` it case it has been removed on a Bullseye or Sid setup.
Therefore, I think I will publish the new release on Monday.

**Comment by dholl** [comment]
Yah, I agree that the couple small package shenanigans I found may not have been from this new ```gandi-hosting-vm2```.

Thanks so much!  This system is now running with only a ```python2``` interpreter and no ```python``` any longer, so hopefully the eventual migration through to stable will be easier.
```
phoenix(pts/1):~# which python
python not found
zsh: exit 1
phoenix(pts/1):~# which python2
/usr/bin/python2
phoenix(pts/1):~#
```

**Comment by David-5-1** [comment]
For the record, the new release is now available in the repository.

Thanks again for your report and feedback.

**Pull request merged**
